version: '3.8'

services:
  siscom-api:
    image: siscom-api:latest
    container_name: siscom-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      # Configuración de Base de Datos
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_MIN_CONNECTIONS: ${DB_MIN_CONNECTIONS}
      DB_MAX_CONNECTIONS: ${DB_MAX_CONNECTIONS}
      DB_CONNECTION_TIMEOUT_SECS: ${DB_CONNECTION_TIMEOUT_SECS}
      DB_IDLE_TIMEOUT_SECS: ${DB_IDLE_TIMEOUT_SECS}
      
      # Seguridad JWT (debes configurar esto en tus secrets de GitHub)
      JWT_SECRET_KEY: ${JWT_SECRET_KEY:-changeme}
      JWT_ALGORITHM: ${JWT_ALGORITHM:-HS256}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES:-60}
      
      # CORS
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS:-*}
      
      # Métricas StatsD
      STATSD_HOST: ${STATSD_HOST:-localhost}
      STATSD_PORT: ${STATSD_PORT:-8126}
      STATSD_PREFIX: ${STATSD_PREFIX:-siscom_api}
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health').read()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - siscom-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  siscom-network:
    external: true

