[pytest]
# Configuración de pytest para SISCOM API
testpaths = test
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# Opciones de asyncio
asyncio_mode = auto

# Mostrar warnings
addopts = 
    -v
    --strict-markers
    --tb=short
    --cov=app
    --cov-report=term-missing
    --cov-report=html
    --cov-branch

# Markers personalizados
markers =
    unit: marca un test como test unitario
    integration: marca un test como test de integración
    slow: marca un test como lento
    auth: tests relacionados con autenticación
    database: tests que requieren base de datos

# Directorio de cobertura
[coverage:run]
source = app
omit = 
    */tests/*
    */test_*
    */__pycache__/*
    */venv/*

[coverage:report]
exclude_lines =
    pragma: no cover
    def __repr__
    raise AssertionError
    raise NotImplementedError
    if __name__ == .__main__.:
    if TYPE_CHECKING:
    @abstractmethod

